language: csharp
dist: trusty
sudo: false

mono: none
dotnet: 2.1.3

install:
  - dotnet restore

script:
  - dotnet build -c Release

deploy:
  provider: script
  skip-cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
    tags: true
